{{/*
ACGS-2 ServiceAccount
Constitutional Hash: cdd01ef066bc6cf2
*/}}
{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "acgs2.serviceAccountName" . }}
  labels:
    {{- include "acgs2.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
